server:
  port: 8080

spring:
  application:
    name: personal_portfolio_backend_java_spring
  data:
    mongodb:
      host: localhost
      port: 27017
      database: portfolio_db

# CORS Configuration
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE
  allowed-headers: "*"
  allow-credentials: true