server:
  port: 8080

spring:
  application:
    name: personal_portfolio_backend_java_spring
  data:
    mongodb:
      uri: mongodb+srv://chaybon894:XBLLv9B8KpQE8doU@portfolio.j6c4qwc.mongodb.net/portfolio_db

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE
  allowed-headers: "*"
  allow-credentials: true
